# Generated by Django 5.2.1 on 2025-07-14 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_user_following_post_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="post",
            name="like_count",
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
